### ISSUE TITLE
winrar-x64-701sc.exe不正确

### ISSUE THREAD

**Issue by tqangxl** [lvtx/WinRAR-Extractor#10]
![image](https://github.com/user-attachments/assets/31986a7b-8d6d-45d3-9d84-e80d7eb4cc38)

**Comment by Goooooooooood** [comment]
遇到了同样的问题。希望以下内容对路过的人有帮助。
32位：
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240528/rrlb/winrar-x32-701sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240528/wrr/winrar-x32-701sc.exe

64位：
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240528/rrlb/winrar-x64-701sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240528/wrr/winrar-x64-701sc.exe
