### ISSUE TITLE
最新的622已无法提取

### ISSUE THREAD

**Issue by suduogou** [lvtx/WinRAR-Extractor#3]
win11 win7 下都测试了，停留在 621

**Comment by TUO1500** [comment]
v6.22链接中日期变了, 是 `20230607`

**Comment by lvtx** [comment]
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20230607/wrr/winrar-x32-622sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20230607/wrr/winrar-x64-622sc.exe

https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20230607/rrlb/winrar-x32-622sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20230607/rrlb/winrar-x64-622sc.exe

**Comment by lvtx** [comment]
> v6.22链接中日期变了, 是`20230607`

已更新v1.0.0.4版本，增加文件下载检测功能，缺点启动会慢一些！
