### ISSUE TITLE
文件打开提示有问题，进入主界面后，无法获取信息

### ISSUE THREAD

**Issue by Ryooen** [lvtx/WinRAR-Extractor#5]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.UriFormatException: 无效的 URI: 此 URI 为空。
   在 System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   在 System.Net.WebRequest.Create(String requestUriString)
   在 WinRAR_Extractor.HttpWebHelper.GetHttpWebData(String url, Nullable`1 timeout, String userAgent, Boolean lastModified) 位置 E:\Tools\系统工具\WinRAR\WinRAR-Extractor\WinRAR-Extractor\HttpWebHelper.cs:行号 41
   在 WinRAR_Extractor.frmExtractor.btnRefresh_Click(Object sender, EventArgs e) 位置 E:\Tools\系统工具\WinRAR\WinRAR-Extractor\WinRAR-Extractor\frmExtractor.cs:行号 87
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.PerformClick()
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.9167.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WinRAR-Extractor
    程序集版本:1.0.0.4
    Win32 版本:1.0.0.4
    基本代码:file:///C:/Users/zhang/Desktop/WinRAR-Extractor_v1.0.0.4_x64_Release/WinRAR-Extractor.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.9075.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.9166.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

![屏幕截图 2023-08-13 153024](https://github.com/lvtx/WinRAR-Extractor/assets/136787396/8581125d-df55-4cf4-8af5-027220eaec2c)
![屏幕截图 2023-08-13 153113](https://github.com/lvtx/WinRAR-Extractor/assets/136787396/7476f665-1a35-4d08-bdae-7648399585c8)

**Comment by Ryooen** [comment]
补充一下，旧版本1.0.0.2打开不会提示错误，不过0.2版本无法获取到版本信息，1.0.0.4和1.0.0.3打开都会有上述错误提示


![屏幕截图 2023-08-13 155535](https://github.com/lvtx/WinRAR-Extractor/assets/136787396/f0409919-d3d9-4c28-8faa-79cc82cae116)
![屏幕截图 2023-08-13 155633](https://github.com/lvtx/WinRAR-Extractor/assets/136787396/aa082a86-df84-4375-bd1e-c279cc139e5d)

**Comment by SunsetMkt** [comment]
在部分情况下，`www.win-rar.com`会禁止特定IP的连接，此时会出现此问题。
