### ISSUE TITLE
大佬，623已经出来了，为啥检测不到呢？

### ISSUE THREAD

**Issue by drw2005** [lvtx/WinRAR-Extractor#6]
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20230808/wrr/winrar-x64-623sc.exe

现在检测到的依然是：
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20230607/wrr/winrar-x64-622sc.exe

**Comment by qinmenghua** [comment]
对，623出来了，但是检测不到

**Comment by lvtx** [comment]
v1.0.0.5 更新了
