### ISSUE TITLE
最新版WinRAR简体中文版无法提取授权文件

### ISSUE THREAD

**Issue by lzxshare** [lvtx/WinRAR-Extractor#7]
如图所示，无法提取授权文件，提示无法加载dll文件

![1694486877943](https://github.com/lvtx/WinRAR-Extractor/assets/39763177/f466c682-d7d5-4748-bbeb-06bee9ab6d35)

**Comment by lzxshare** [comment]
啥意思呢，没有任何说明就直接关闭了Issues

**Comment by lvtx** [comment]
> 啥意思呢，没有任何说明就直接关闭了Issues

就你一人出现这样的问题，那就请自行找原因呗，代码都是开源的，写这工具纯粹个人兴趣爱好，我不提供任何服务！
